[tools]
# Shell linting and formatting tools
shellcheck = "latest"
shfmt = "latest"

# Security scanning
gitleaks = "latest"

# General development tools
pre-commit = "latest"

# Required by dotfiles cogs
fzf = "latest"
neovim = "latest"

[env]
# Ensure tools are available in PATH
_.path = ["{{ config_root }}/bin"]
