runtime bundle/vim-pathogen/autoload/pathogen.vim " Loading pathogen 
execute pathogen#infect()

let g:airline_powerline_fonts = 1 " use powerline fonts
set laststatus=2            " make airline show up with at once

syntax enable
set background=dark
"let g:solarized_termcolors=256 fix for not having solarized terminal palette
colorscheme base16-twilight " Remember to add terminal palette

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_sh_shellcheck_args = "-s bash"

set rtp+=~/.fzf

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^linux'
  set t_Co=16
endif

set backspace=indent,eol,start " So that backspace will 'work'

set tabstop=2           	" 4 space tab
set expandtab           	" use spaces for tabs
set softtabstop=2       	" 4 space tab
set shiftwidth=2
filetype plugin on          " detect filetype
filetype indent on          " and indent accordingly
set number                  " show line numbers
set showcmd                 " show command in bottom bar
set cursorline              " highlight current line

set foldmethod=syntax       " fold based on indent level
set foldnestmax=10          " max 10 depth
set foldenable              " don't fold files by default on open

set backupdir=~/.vim/.backup// " don't make a mess
set directory=~/.vim/.swp//    " not even for swap files

" Have vim put the cursor where it was the last time we viewed this file
autocmd BufReadPost *
  \ if line("'\"") >= 1 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif
